config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'posts#index'

  resources :posts do
    resources :comments
  end

  get 'my_posts', to: 'posts#my_posts'
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'slider', to: 'slider#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :body, presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_taggable
  ## Associations, delegates
  belongs_to :user
  has_many :comments, dependent: :destroy

  ## Validations
  validates :title, :text, :published_at, presence: true

  paginates_per 5

  scope :by_published, -> { where(published: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Associations, delegates
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post, only: [:create, :destroy, :update, :edit, :find_comment]
  before_action :find_comment, only: [:update, :destroy]
  respond_to :html, :json

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @comment.update_attributes(comment_params)
        format.json { respond_with_bip(@comment) }
      else
        format.json { respond_with_bip(@comment) }
      end
    end
  end

  def destroy
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params[:comment].merge!(user_id: current_user.id)
    params.require(:comment).permit(:body, :user_id, :published_at)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_comment
    @comment = @post.comments.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post, only: [:show, :destroy, :edit, :update]

  def index
    @posts = if params[:tag]
      Post.by_published.page(params[:page]).order('created_at DESC').tagged_with(params[:tag])
    else
      Post.by_published.page(params[:page]).order('created_at DESC')
    end
  end

  def new
    @post = Post.new
  end

  def show
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.published_at = Time.now
    if @post.save
      flash[:success] = 'Пост успешно создан'
      redirect_to my_posts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to(@post)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:alert] = 'Пост успешно удален'
    redirect_to my_posts_path
  end

  def my_posts
    @posts = current_user.posts.page(params[:page]).order('created_at DESC')
  end

  def tag_cloud
    @tags = Post.tag_counts_on(:tags)
  end

  private

  def post_params
    params[:post].permit(:title, :text, :published_at, :tag_list)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/slider_controller.rb
class SliderController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    { success: 'alert-success', error: 'alert-error', alert: 'alert-warning', notice: 'alert-info' }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
        concat content_tag(:button, 'x', class: 'close', data: { dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end

  def submit_text_button(object)
    object.new_record? ? 'Создать' : 'Обновить'
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/comments/_comment.html.slim
/ .col-xs-8.col-sm-6
/   small= "#{comment.user.email.match(/(.*)@/)[1]} #{comment.created_at.strftime('%d/%m/%Y')}"
/   '
/   strong
/     = best_in_place_if comment.decorate.author?(comment.user), [comment.post, comment], :body, as: :textarea
/ .col-xs-4.col-sm-6
dl.dl-horizontal
  dt= "#{comment.user.email.match(/(.*)@/)[1]} #{comment.created_at.strftime('%d/%m/%Y')}"
  dd
    = best_in_place_if comment.decorate.author?(comment.user), [comment.post, comment], :body, as: :textarea
    '
    - if comment.decorate.author?(comment.user)
      = link_to [comment.post, comment], method: :delete do
        span.glyphicon.glyphicon-remove-circle

app/views/comments/_form.html.slim
= simple_form_for [@post, @post.comments.build] do |f|
  = f.input :body
  = f.button :submit, 'Добавить', class: 'btn btn-success'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Igooods
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-default.navbar-static-top
      .container
        - if current_user
          p.navbar-text
            = link_to 'Блог', root_path, class: 'navbar-link'
          p.navbar-text
            = link_to 'Мои посты', my_posts_path, class: 'navbar-link'
          p.navbar-text
            = link_to 'Слайдер', slider_path, class: 'navbar-link'
          
          = link_to 'Добавить статью', new_post_path, class: 'btn btn-info btn-sm navbar-btn'
          = link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'btn btn-danger btn-sm navbar-btn navbar-right'
    .container
      = flash_messages
      = yield

app/views/posts/_form.html.slim
.col-md-6
  = simple_form_for @post, html: { class: 'form-horizontal' } do |f|
    = f.input :title
    = f.input :text, input_html: { rows: 10 }
    = f.input :tag_list, label: 'Теги'
    - unless @post.new_record?
      = f.input :published_at, input_html: { class: 'datepicker', value: @post.decorate.date_creation } , as: :string
    = f.input :published, as: :boolean, checked_value: true, unchecked_value: false
    = f.button :submit, submit_text_button(@post), class: 'btn btn-success'

app/views/posts/_post.html.slim
.section
  section.articles
    .article
      header
        = link_to post.title, post_path(post)
        span
          = "#{post.user.email.match(/(.*)@/)[1]} #{post.created_at.strftime('%d/%m/%Y')}"
      p= post.text

app/views/posts/_posts.html.slim
.row
  .col-md-8
    = render partial: 'post', collection: @posts
  = paginate @posts
  .col-md-4
    - tag_cloud Post.tag_counts, %w(css1 css2 css3) do |tag, css_class|
      = link_to tag.name, tag_path(tag.name), class: css_class

app/views/posts/edit.html.slim
= render 'form'

app/views/posts/index.html.slim
= render 'posts'

app/views/posts/my_posts.html.slim
= render partial: 'post', collection: @posts
= paginate @posts

app/views/posts/new.html.slim
= render 'form'

app/views/posts/show.html.slim
= render partial: 'post', locals: { post: @post }
.row
  .col-md-2.col-md-offset-9
    = link_to 'Редактировать', edit_post_path(@post), class: 'btn btn-warning btn-block'
    = link_to 'Удалить', post_path(@post), method: :delete, class: 'btn btn-danger btn-block'

.row
  h5 Комментарии
  = render @post.comments.includes(:user)

.row
  .col-xs-12.col-md-8
    = render 'comments/form'
 

app/views/slider/index.html.slim
.slider__wrapper
  .slider
    = image_tag "slide1.jpg", class: 'slider_slide'
    = image_tag "slide2.jpg", class: 'slider_slide'
    = image_tag "slide3.jpg", class: 'slider_slide'
  .slider_info
    p.slider_info_text
      | Фотографиям вашего ребенка
      br>/
      | позавидуют даже звезды
      a.slider_info_button href="#"  начать обучение &raquo;
    .arrow_left &laquo;
    .arrow_right &raquo;